// <auto-generated />
using System;
using FacilityLeasing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacilityLeasing.Migrations;

[DbContext(typeof(FacilityManagementDbContext))]
partial class FacilityManagementDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("FacilityLeasing.Entities.EquipmentPlacementContract", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("EquipmentUnits")
                    .HasColumnType("int");

                b.Property<string>("ProcessEquipmentTypeCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("ProductionFacilityCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.HasIndex("ProcessEquipmentTypeCode");

                b.HasIndex("ProductionFacilityCode");

                b.ToTable("EquipmentPlacementContracts");
            });

        modelBuilder.Entity("FacilityLeasing.Entities.ProcessEquipmentType", b =>
            {
                b.Property<string>("Code")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<double>("Area")
                    .HasColumnType("float");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Code");

                b.ToTable("ProcessEquipmentTypes");
            });

        modelBuilder.Entity("FacilityLeasing.Entities.ProductionFacility", b =>
            {
                b.Property<string>("Code")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<double>("StandardArea")
                    .HasColumnType("float");

                b.HasKey("Code");

                b.ToTable("ProductionFacilities");
            });

        modelBuilder.Entity("FacilityLeasing.Entities.EquipmentPlacementContract", b =>
            {
                b.HasOne("FacilityLeasing.Entities.ProcessEquipmentType", "ProcessEquipmentType")
                    .WithMany("EquipmentPlacementContracts")
                    .HasForeignKey("ProcessEquipmentTypeCode")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("FacilityLeasing.Entities.ProductionFacility", "ProductionFacility")
                    .WithMany("EquipmentPlacementContracts")
                    .HasForeignKey("ProductionFacilityCode")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ProcessEquipmentType");

                b.Navigation("ProductionFacility");
            });

        modelBuilder.Entity("FacilityLeasing.Entities.ProcessEquipmentType", b =>
            {
                b.Navigation("EquipmentPlacementContracts");
            });

        modelBuilder.Entity("FacilityLeasing.Entities.ProductionFacility", b =>
            {
                b.Navigation("EquipmentPlacementContracts");
            });
#pragma warning restore 612, 618
    }
}
