name: Build and deploy ASP.Net Core app to Azure Web App - FacilityManagementWebAPI-dev

on:
  push:
    branches:
      - main

permissions:
  id-token: write 

jobs:
  build:
    runs-on: windows-latest

    env:
      BUILD_CONFIGURATION: Release
      DOTNET_VERSION: 8.0
      DATABASE_CONNECTION: ${{ secrets.DATABASE_CONNECTION }}

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Install NuGet Tool
      - name: Install NuGet Tool
        run: nuget install -Version latest

      # Restore NuGet Packages
      - name: Restore NuGet Packages
        run: dotnet restore "FacilityLeasing.sln"

      # Build the solution
      - name: Build Solution
        run: dotnet build "FacilityLeasing/FacilityLeasing.csproj" --configuration ${{ env.BUILD_CONFIGURATION }}

      # Run tests
      - name: Run Tests
        run: dotnet test "FacilityLeasing.sln" --configuration ${{ env.BUILD_CONFIGURATION }}

      # Publish the project
      - name: Publish Project
        run: dotnet publish "FacilityLeasing/FacilityLeasing.csproj" --configuration ${{ env.BUILD_CONFIGURATION }} --output ./publish

      # Install dotnet-ef globally
      - name: Install dotnet-ef Tool
        run: dotnet tool install --global dotnet-ef --version 8.0.8

      # Add EF Tool to PATH
      - name: Add EF Tool to PATH
        run: echo "${{ github.workspace }}/.dotnet/tools" >> $GITHUB_PATH

      # Apply Entity Framework Migrations
      - name: Apply EF Migrations
        run: dotnet ef database update --connection ${{ env.DATABASE_CONNECTION }} --configuration ${{ env.BUILD_CONFIGURATION }} --startup-project FacilityLeasing/FacilityLeasing.csproj --project FacilityLeasing/FacilityLeasing.csproj


      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./publish


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_39CCEEC2E1564F64A3753C23EEB9DF89 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E196D3EB86F244ED8C75BD339FBB6ACE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F504A0FA43B64BE3B447357F543BC334 }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FacilityManagementWebAPI-dev'
          slot-name: 'Production'
          package: ./publish 
          
